version: '3'
services:
  petclinic:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_USER=petclinic
      - POSTGRES_PASS=petclinic
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/petclinic
      
    depends_on:
      - postgres  
    networks:
      - webnet  
  postgres:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    networks:
      - webnet  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - petclinic
    networks:
      - webnet  


networks:
  webnet:
